fix(bin): improve error message for unrecognized commands and update package dependencies

diff --git a/bin/_/£ b/bin/_/£
--- a/bin/_/£
+++ b/bin/_/£
@@ -92,7 +92,8 @@ else
     echo_spacex2
     ;;
   *)
-    echo 'What did you say?'
+    echo "Error: Unrecognized command '$1'. Use --help for a list of commands."
+    exit 1
     ;;
   esac
 
